# Generated by Django 6.1 on 2026-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_consumable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_durable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(choices=[('BEAUTY', 'Beauty & Personal Care'), ('PERSONAL_ELECTRICAL', 'Personal Electrical'), ('HOME_APPLIANCE', 'Home Appliance'), ('OTHER', 'Other')], db_index=True, default='BEAUTY', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='repurchase_cycle_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of days before the customer typically repurchases this product.', null=True),
        ),
    ]
