# Generated by Django 6.1 on 2026-10-07 07:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('TOMAN', 'تومان')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('source_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_price', to='products.product')),
            ],
            options={
                'verbose_name': 'قیمت پایه داده آزمایشی',
                'verbose_name_plural': 'قیمت\u200cهای پایه داده آزمایشی',
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='demo_price_nonnegative'), models.CheckConstraint(condition=models.Q(('currency', 'TOMAN')), name='demo_price_currency_toman'), models.CheckConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('source_version', ''), _negated=True)), name='demo_price_source_required')],
            },
        ),
    ]
