# Generated by Django 6.1 on 2026-08-24 07:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
        ('visits', '0004_salesperson_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('scope_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('PRODUCT_GROUP', 'Product Group')], db_index=True, max_length=20)),
                ('product_group', models.CharField(blank=True, choices=[('BEAUTY', 'Beauty & Personal Care'), ('PERSONAL_ELECTRICAL', 'Personal Electrical'), ('HOME_APPLIANCE', 'Home Appliance'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('target_unit', models.CharField(choices=[('QUANTITY', 'Quantity'), ('MSU', 'MSU')], default='QUANTITY', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='products.product')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_targets', to='visits.salesperson')),
            ],
            options={
                'ordering': ['period_start', 'salesperson_id', 'scope_type', 'id'],
                'indexes': [models.Index(fields=['salesperson', 'period_start', 'period_end', 'is_active'], name='targets_sal_salespe_3847e2_idx'), models.Index(fields=['scope_type', 'is_active'], name='targets_sal_scope_t_4dc2b1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='sales_target_value_gt_zero'), models.CheckConstraint(condition=models.Q(('actual_value__gte', 0)), name='sales_target_actual_gte_zero'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('product__isnull', False), ('product_group__isnull', True), ('scope_type', 'PRODUCT')), models.Q(('category__isnull', False), ('product__isnull', True), ('product_group__isnull', True), ('scope_type', 'CATEGORY')), models.Q(('category__isnull', True), ('product__isnull', True), ('product_group__isnull', False), ('scope_type', 'PRODUCT_GROUP')), _connector='OR'), name='sales_target_valid_scope'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'PRODUCT')), fields=('salesperson', 'period_start', 'period_end', 'product', 'target_unit'), name='unique_active_product_target'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'CATEGORY')), fields=('salesperson', 'period_start', 'period_end', 'category', 'target_unit'), name='unique_active_category_target'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'PRODUCT_GROUP')), fields=('salesperson', 'period_start', 'period_end', 'product_group', 'target_unit'), name='unique_active_product_group_target')],
            },
        ),
    ]
