# Generated by Django 6.1 on 2026-08-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('STORE', 'Store'), ('SALON', 'Beauty Salon'), ('PHARMACY', 'Pharmacy'), ('DISTRIBUTOR', 'Distributor'), ('OTHER', 'Other')], default='STORE', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Customer360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('first_purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_since_last_purchase', models.PositiveIntegerField(default=0)),
                ('recency_score', models.PositiveSmallIntegerField(default=0)),
                ('frequency_score', models.PositiveSmallIntegerField(default=0)),
                ('monetary_score', models.PositiveSmallIntegerField(default=0)),
                ('rfm_score', models.PositiveSmallIntegerField(default=0)),
                ('segment', models.CharField(choices=[('HIGH_VALUE', 'High Value'), ('GROWTH', 'Growth'), ('STABLE', 'Stable'), ('AT_RISK', 'At Risk'), ('INACTIVE', 'Inactive'), ('NEW', 'New')], default='NEW', max_length=20)),
                ('top_category', models.CharField(blank=True, max_length=100)),
                ('top_product_code', models.CharField(blank=True, max_length=50)),
                ('sales_30d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sales_90d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sales_30d_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sales_90d_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_360', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer 360',
                'verbose_name_plural': 'Customers 360',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customergrade'),
        ),
    ]
