# Generated by Django 6.1 on 2026-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('STORE', 'Store'), ('DISTRIBUTOR', 'Distributor'), ('WHOLESALER', 'Wholesaler'), ('ELECTRICAL_STORE', 'Electrical Store'), ('HOME_APPLIANCE_STORE', 'Home Appliance Store'), ('OTHER', 'Other')], default='STORE', max_length=30),
        ),
    ]
