# Generated by Django 6.1 on 2026-08-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('promotion_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Discount'), ('BUY_X_GET_Y', 'Buy X Get Y')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_grades', models.ManyToManyField(blank=True, related_name='promotions', to='customers.customergrade')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_products', to='products.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='promotions.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'product')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', through='promotions.PromotionProduct', to='products.product'),
        ),
    ]
