# Generated by Django 6.1 on 2026-08-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='GENERATED', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='products.product')),
            ],
            options={
                'ordering': ['customer', 'rank'],
            },
        ),
    ]
