# Generated by Django 6.1 on 2026-08-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['rank', '-score']},
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('CROSS_SELL', 'Cross Sell'), ('UP_SELL', 'Up Sell'), ('REPLENISHMENT', 'Replenishment'), ('DISCOVERY', 'Discovery')], default='DISCOVERY', max_length=30),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['customer', 'is_active', 'rank'], name='recommendat_custome_f93f17_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'recommendation_type'), name='unique_customer_product_recommendation'),
        ),
    ]
