# Generated by Django 6.1 on 2026-08-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
        ('recommendations', '0002_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('CROSS_SELL', 'Cross Sell'), ('REPEAT_PURCHASE', 'Repeat Purchase'), ('SIMILAR_PRODUCT', 'Similar Product'), ('CATEGORY', 'Category Recommendation')], max_length=30)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('reason', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', 'rank'],
            },
        ),
        migrations.RemoveIndex(
            model_name='recommendation',
            name='recommendat_custome_f93f17_idx',
        ),
        migrations.RemoveConstraint(
            model_name='recommendation',
            name='unique_customer_product_recommendation',
        ),
        migrations.AddField(
            model_name='customerrecommendation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='product',
        ),
        migrations.AddIndex(
            model_name='customerrecommendation',
            index=models.Index(fields=['customer', 'is_active'], name='recommendat_custome_73ce2d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrecommendation',
            index=models.Index(fields=['customer', 'recommendation_type'], name='recommendat_custome_9fd245_idx'),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
