# Generated by Django 6.1 on 2026-08-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
        ('recommendations', '0003_customerrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('support', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('lift', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_from', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='products.product')),
            ],
            options={
                'ordering': ['-lift', '-confidence', '-occurrence_count'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='recommendat_product_e94d78_idx'), models.Index(fields=['associated_product', 'is_active'], name='recommendat_associa_946a01_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'associated_product'), name='unique_product_association')],
            },
        ),
    ]
