# Generated by Django 6.1 on 2026-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_productassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('CROSS_SELL', 'Cross Sell'), ('REPEAT_PURCHASE', 'Repeat Purchase'), ('SIMILAR_PRODUCT', 'Similar Product'), ('CATEGORY', 'Category Recommendation'), ('UP_SELL', 'Up Sell')], max_length=30),
        ),
    ]
