# Generated by Django 6.1 on 2026-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('products', '0002_alter_category_options_product_is_consumable_and_more'),
        ('recommendations', '0005_alter_customerrecommendation_recommendation_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'product'), name='unique_active_customer_product_recommendation'),
        ),
    ]
