# Generated by Django 6.1 on 2026-08-17 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_customerrecommendation_unique_active_customer_product_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_recommendation_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('max_recommendations', models.PositiveIntegerField(default=5)),
                ('category_rank_1_score', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6)),
                ('category_rank_2_score', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=6)),
                ('category_rank_3_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('category_rank_4_score', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6)),
                ('category_rank_5_score', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6)),
                ('category_rank_6_score', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6)),
                ('category_rank_7_score', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=6)),
                ('category_rank_8_score', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=6)),
                ('category_rank_9_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('category_rank_10_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('category_rank_11_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('grade_a_score', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6)),
                ('grade_b_score', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6)),
                ('grade_c_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('promotion_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('association_max_score', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6)),
                ('association_lift_max_score', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6)),
                ('association_evidence_1_score', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('association_evidence_2_score', models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=6)),
                ('association_evidence_3_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('repurchase_no_cycle_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('repurchase_overdue_30_score', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=6)),
                ('repurchase_overdue_90_score', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=6)),
                ('repurchase_overdue_high_score', models.DecimalField(decimal_places=2, default=Decimal('45'), max_digits=6)),
                ('durable_previous_purchase_score', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('upsell_10_percent_score', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6)),
                ('upsell_25_percent_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('upsell_50_percent_score', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6)),
                ('upsell_high_score', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=6)),
                ('similar_product_score', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
