# Generated by Django 6.1 on 2026-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_recommendationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecommendation',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
