# Generated by Django 6.1 on 2026-08-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_customerrecommendation_score_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTuningSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(blank=True, choices=[('CROSS_SELL', 'Cross Sell'), ('REPEAT_PURCHASE', 'Repeat Purchase'), ('SIMILAR_PRODUCT', 'Similar Product'), ('CATEGORY', 'Category Recommendation'), ('UP_SELL', 'Up Sell')], max_length=30)),
                ('metric', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('suggested_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('reason', models.TextField(blank=True)),
                ('performance_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
