# Generated by Django 6.1 on 2026-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_recommendationtuningsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationtuningsuggestion',
            name='applied_previous_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recommendationtuningsuggestion',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationtuningsuggestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('ROLLED_BACK', 'Rolled Back')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
