# Generated by Django 6.1 on 2026-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_recommendationtuningsuggestion_applied_previous_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecommendation',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='customerrecommendation',
            name='evidence_quality',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='customerrecommendation',
            name='explanation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
