# Generated by Django 6.1 on 2026-10-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_customerrecommendation_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADDED_TO_REQUEST', 'افزوده\u200cشده به درخواست'), ('REMOVED_FROM_REQUEST', 'حذف\u200cشده از درخواست'), ('REJECTED', 'رد پیشنهاد')], max_length=24)),
                ('reason_code', models.CharField(blank=True, choices=[('NOT_INTERESTED', 'مشتری علاقه\u200cمند نبود'), ('PRICE', 'قیمت مناسب نبود'), ('STOCK', 'موجودی کافی نبود'), ('NO_CURRENT_NEED', 'فعلاً نیاز ندارد'), ('OTHER_BRAND', 'قبلاً از برند/مدل دیگری استفاده می\u200cکند'), ('LATER', 'بعداً پیگیری شود'), ('OTHER', 'دلیل دیگر')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('lineage_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رویداد بازخورد پیشنهاد',
                'verbose_name_plural': 'رویدادهای بازخورد پیشنهاد',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
