# Generated by Django 6.1 on 2026-10-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_recommendationfeedbackevent'),
        ('sales_requests', '0001_initial'),
        ('visits', '0007_alter_visitcommercialsnapshot_target_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationfeedbackevent',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_events', to='sales_requests.salesrequestline'),
        ),
        migrations.AddField(
            model_name='recommendationfeedbackevent',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_events', to='recommendations.customerrecommendation'),
        ),
        migrations.AddField(
            model_name='recommendationfeedbackevent',
            name='sales_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_events', to='sales_requests.salesrequest'),
        ),
        migrations.AddField(
            model_name='recommendationfeedbackevent',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_feedback_events', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['ADDED_TO_REQUEST', 'REMOVED_FROM_REQUEST', 'REJECTED'])), name='rfe_valid_event_type'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'REJECTED'), ('reason_code__in', ['NOT_INTERESTED', 'PRICE', 'STOCK', 'NO_CURRENT_NEED', 'OTHER_BRAND', 'LATER', 'OTHER'])), models.Q(('event_type__in', ['ADDED_TO_REQUEST', 'REMOVED_FROM_REQUEST']), ('reason_code', '')), _connector='OR'), name='rfe_rejection_reason'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type', 'REJECTED'), models.Q(('line__isnull', False), ('sales_request__isnull', False)), _connector='OR'), name='rfe_acceptance_has_line'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedbackevent',
            constraint=models.CheckConstraint(condition=models.Q(('line__isnull', True), ('sales_request__isnull', False), _connector='OR'), name='rfe_line_has_request'),
        ),
    ]
