# Generated by Django 6.1 on 2026-10-07 07:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productdemoprice'),
        ('recommendations', '0012_recommendationfeedbackevent'),
        ('visits', '0007_alter_visitcommercialsnapshot_target_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('SUBMITTED', 'ثبت\u200cشده')], default='DRAFT', max_length=12)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('submission_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('submission_intent_hash', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA256 intent fingerprint.')])),
                ('note', models.CharField(blank=True, max_length=500)),
                ('base_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('TOMAN', 'تومان')], max_length=10, null=True)),
                ('customer_snapshot', models.JSONField(blank=True, default=dict)),
                ('salesperson_snapshot', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('prepared_message_snapshot', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_request', to='visits.visit')),
            ],
            options={
                'verbose_name': 'درخواست فروش',
                'verbose_name_plural': 'درخواست\u200cهای فروش',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesRequestAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_request_acknowledgements', to='visits.salesperson')),
                ('sales_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgement', to='sales_requests.salesrequest')),
            ],
            options={
                'verbose_name': 'تأیید مشاهده درخواست فروش',
                'verbose_name_plural': 'تأییدهای مشاهده درخواست فروش',
            },
        ),
        migrations.CreateModel(
            name='SalesRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_selected', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('selection_source', models.CharField(choices=[('ORDINARY', 'انتخاب عادی'), ('RECOMMENDATION', 'پیشنهاد اولویت\u200cدار')], default='ORDINARY', max_length=20)),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('lineage_snapshot', models.JSONField(blank=True, default=dict)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('base_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('TOMAN', 'تومان')], max_length=10, null=True)),
                ('pricing_source', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_request_lines', to='products.product')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_request_lines', to='recommendations.customerrecommendation')),
                ('sales_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales_requests.salesrequest')),
            ],
            options={
                'verbose_name': 'قلم درخواست فروش',
                'verbose_name_plural': 'اقلام درخواست فروش',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED'])), name='sr_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 0)), name='sr_nonnegative_revision'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('number__isnull', True), models.Q(('number', ''), _negated=True), _connector='OR'), name='sr_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('currency__isnull', True), ('currency', 'TOMAN'), _connector='OR'), name='sr_currency_toman'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('base_total__isnull', True), ('base_total__gte', 0), _connector='OR'), name='sr_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__isnull', True), ('discount_total__gte', 0), _connector='OR'), name='sr_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('final_total__isnull', True), ('final_total__gte', 0), _connector='OR'), name='sr_final_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('submitted_at__isnull', True)), models.Q(('base_total__isnull', False), ('currency', 'TOMAN'), ('discount_total__isnull', False), ('final_total__isnull', False), ('number__isnull', False), ('status', 'SUBMITTED'), ('submission_intent_hash__isnull', False), ('submission_key__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='sr_submission_fields'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='srl_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('sales_request', 'product'), name='srl_unique_selected_product'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_selected', True), ('removed_at__isnull', True)), models.Q(('is_selected', False), ('removed_at__isnull', False)), _connector='OR'), name='srl_removal_fields'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recommendation__isnull', True), ('selection_source', 'ORDINARY')), models.Q(('recommendation__isnull', False), ('selection_source', 'RECOMMENDATION')), _connector='OR'), name='srl_lineage_source'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('currency__isnull', True), ('currency', 'TOMAN'), _connector='OR'), name='srl_currency_toman'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('base_unit_price__isnull', True), ('base_unit_price__gte', 0), _connector='OR'), name='srl_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__isnull', True), models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), _connector='OR'), name='srl_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__isnull', True), ('discount_amount__gte', 0), _connector='OR'), name='srl_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('final_unit_price__isnull', True), ('final_unit_price__gte', 0), _connector='OR'), name='srl_final_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__isnull', True), ('line_total__gte', 0), _connector='OR'), name='srl_total_nonnegative'),
        ),
    ]
