# Generated by Django 6.1 on 2026-10-08 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_requests', '0001_initial'),
        ('visits', '0007_alter_visitcommercialsnapshot_target_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRequestMutationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_uuid', models.UUIDField()),
                ('operation', models.CharField(choices=[('ADD_PRODUCT', 'افزودن محصول'), ('SET_QUANTITY', 'تغییر تعداد'), ('REMOVE_PRODUCT', 'حذف محصول'), ('REJECT_RECOMMENDATION', 'رد پیشنهاد')], max_length=24)),
                ('intent_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Expected a SHA256 intent fingerprint.')])),
                ('applied_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_request_mutation_receipts', to=settings.AUTH_USER_MODEL)),
                ('sales_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutation_receipts', to='sales_requests.salesrequest')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutation_receipts', to='visits.visit')),
            ],
            options={
                'verbose_name': 'رسید اجرای فرمان درخواست فروش',
                'verbose_name_plural': 'رسیدهای اجرای فرمان درخواست فروش',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('visit', 'command_uuid'), name='srmr_unique_visit_command'), models.CheckConstraint(condition=models.Q(('operation__in', ['ADD_PRODUCT', 'SET_QUANTITY', 'REMOVE_PRODUCT', 'REJECT_RECOMMENDATION'])), name='srmr_valid_operation'), models.CheckConstraint(condition=models.Q(('intent_fingerprint', ''), _negated=True), name='srmr_intent_not_empty'), models.CheckConstraint(condition=models.Q(models.Q(('applied_revision__isnull', True), ('sales_request__isnull', True)), models.Q(('applied_revision__gte', 0), ('applied_revision__isnull', False), ('sales_request__isnull', False)), _connector='OR'), name='srmr_revision_request_pair')],
            },
        ),
    ]
