# Generated by Django 6.1 on 2026-08-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_customerrecommendation_unique_active_customer_product_recommendation'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('PURCHASED', 'خرید شد'), ('INTERESTED', 'علاقه\u200cمند شد'), ('FOLLOW_UP', 'نیاز به پیگیری'), ('REJECTED', 'رد شد'), ('NOT_PRESENTED', 'مطرح نشد')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_outcomes', to='recommendations.customerrecommendation')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_outcomes', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outcome', 'created_at'], name='visits_sale_outcome_30d95b_idx'), models.Index(fields=['visit', 'outcome'], name='visits_sale_visit_i_39869f_idx'), models.Index(fields=['recommendation', 'outcome'], name='visits_sale_recomme_21b212_idx')],
            },
        ),
    ]
