# Generated by Django 6.1 on 2026-08-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('visits', '0002_salesoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('DONE', 'انجام شده'), ('CANCELLED', 'لغو شده')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks', to='customers.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks', to='visits.salesperson')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks', to='visits.visit')),
            ],
            options={
                'ordering': ['status', 'due_date', 'id'],
            },
        ),
    ]
