# Generated by Django 6.1 on 2026-08-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('visits', '0004_salesperson_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCustomerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_grade_code', models.CharField(blank=True, max_length=50, null=True)),
                ('segment', models.CharField(blank=True, max_length=30, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('days_since_last_purchase', models.PositiveIntegerField(default=0)),
                ('recency_score', models.PositiveIntegerField(default=0)),
                ('frequency_score', models.PositiveIntegerField(default=0)),
                ('monetary_score', models.PositiveIntegerField(default=0)),
                ('rfm_score', models.PositiveIntegerField(default=0)),
                ('top_category', models.CharField(blank=True, max_length=200, null=True)),
                ('top_product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('source_customer360_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_snapshots', to='customers.customer')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_snapshot', to='visits.visit')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
    ]
