# Generated by Django 6.1 on 2026-08-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_type'),
        ('visits', '0005_visitcustomersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCommercialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('commercial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commercial_priority', models.CharField(blank=True, max_length=30, null=True)),
                ('commercial_blocked', models.BooleanField(default=False)),
                ('target_context', models.JSONField(blank=True, default=dict)),
                ('inventory_context', models.JSONField(blank=True, default=dict)),
                ('promotion_context', models.JSONField(blank=True, default=list)),
                ('commercial_signals', models.JSONField(blank=True, default=list)),
                ('decision_reasons', models.JSONField(blank=True, default=list)),
                ('why_now', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_visit_snapshots', to='customers.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_visit_snapshots', to='visits.salesperson')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_snapshot', to='visits.visit')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
    ]
