# Generated by Django 6.1 on 2026-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_visitcommercialsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcommercialsnapshot',
            name='target_context',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
